var BadWords = [
    profanities = [
        " bitch ",
        " fuck ",
        " shit ",
        " sex ",
        " porn ",
        " dick ",
        " penis ",
        " faggot ",
        " cum ",
        " arse ",
        " ass ",
        " bastard ",
        " nigga ",
        " nigger ",
        " piss ",
        " whore ",
        " slut ",
        " prostitute ",
        " frigger ",
        " prick ",
        " cuck ",
    ]
];